# Generated by Django 3.1.5 on 2021-01-27 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210107_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='com_endereco',
            field=models.BooleanField(default=False),
        ),
    ]
