# Generated by Django 3.1.5 on 2021-01-13 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0002_auto_20210111_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='tipo_doacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacao', to='doacao.tipodoacao'),
        ),
        migrations.AlterField(
            model_name='doacao',
            name='tipo_planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacao', to='doacao.tipoplanta'),
        ),
    ]
