# Generated by Django 3.1.5 on 2021-02-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0003_auto_20210112_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='titulo',
            field=models.CharField(default='novo', max_length=20),
            preserve_default=False,
        ),
    ]
