# Generated by Django 3.1.5 on 2021-02-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doacao', '0004_doacao_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='peso',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=10),
        ),
    ]
